import HeroBanner from '@/components/HeroBanner';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta
          name='description'
          content='E-commerce app Generated by create next app'
        />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <HeroBanner />
      </main>
    </>
  );
}
