import HeroBanner from '@/components/HeroBanner';
import Head from 'next/head';
import ProductList from '@/components/ProductList';
import { sanityClient } from '../utils/sanity';
import { IBanner, IProduct } from 'typing';
import FooterBanner from '@/components/FooterBanner';

type Props = {
  dataBanner: IBanner;
  dataProduct: IProduct[];
};

export default function Home({ dataBanner, dataProduct }: Props) {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta
          name='description'
          content='E-commerce app Generated by create next app'
        />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='flex w-full flex-col items-center overflow-hidden bg-base-300 pb-10'>
        <HeroBanner data={dataBanner} />
        <ProductList data={dataProduct} />
        <FooterBanner data={dataBanner} />
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const queryBanner = `*[_type == "banner" ][0]{
      buttonText, 
      desc, 
      discount, 
      image, 
      largeText1, 
      largeText2, 
      midText, 
      product, 
      saleTime, 
      smallText
    }`;
  const queryProduct = `*[_type == "product" ]{
    _id,
    image,
    name,
    price,
    slug,
    details
  }`;

  const dataBanner = await sanityClient.fetch(queryBanner);
  const dataProduct = await sanityClient.fetch(queryProduct);
  return {
    props: {
      dataBanner,
      dataProduct
    }
  };
};
